    const fretMarkers = new Set([3, 5, 7, 9, 12, 15, 17, 19, 21, 24]);
    const text = {
      zh: {
        documentTitle: "吉他指板音阶练习",
        appTitle: "吉他指板音阶练习",
        appSubtitle: "标准六弦，固定调 / 首调，音阶可视化，点击式出题练习。",
        tonalityGroupTitle: "调性",
        materialGroupTitle: "音阶与琶音",
        fretboardGroupTitle: "指板",
        drillGroupTitle: "练习偏好",
        languageLabel: "语言",
        keyLabel: "调",
        accidentalLabel: "升降号",
        materialLabel: "素材",
        modeLabel: "类型",
        fretCountLabel: "显示品数",
        fretWindowLabel: "视图范围",
        visibilityLabel: "调内显示",
        solfegeLabel: "显示体系",
        noteNameLabel: "音名",
        practiceLabel: "练习",
        scalePanelTitle: "当前素材",
        practicePanelTitle: "出题练习",
        practiceTypeLabel: "题型",
        chordPanelTitle: "和弦识别",
        chordPositionLabel: "把位范围",
        metronomeTitle: "节拍器",
        tempoLabel: "速度",
        accidentalOptions: { sharp: "升号 C#", flat: "降号 Db" },
        fretWindowOptions: { auto: "自动", all: "全部品位" },
        chordPositionOptions: { all: "全部品位" },
        materialOptions: { scale: "音阶", arpeggio: "琶音" },
        modeOptions: {
          major: "大调",
          naturalMinor: "自然小调",
          harmonicMinor: "和声小调",
          melodicMinor: "爵士旋律小调",
          majorPentatonic: "大调五声音阶",
          minorPentatonic: "小调五声音阶",
          majorTriad: "大三和弦琶音",
          minorTriad: "小三和弦琶音",
          diminishedTriad: "减三和弦琶音",
          augmentedTriad: "增三和弦琶音",
          major7: "大七和弦琶音",
          dominant7: "属七和弦琶音",
          minor7: "小七和弦琶音",
          halfDiminished7: "半减七和弦琶音",
          diminished7: "减七和弦琶音",
          minorMajor7: "小大七和弦琶音"
        },
        visibilityOptions: { highlight: "所有音可见，调内音高亮", scaleOnly: "只显示调内音" },
        solfegeOptions: { fixed: "固定调：音名", movableNote: "首调：音名", degree: "首调：级数" },
        practiceTypeOptions: {
          findNote: "给音名，点击位置",
          identifyPosition: "给位置，识别音名",
          findDegree: "给级数，点击对应音",
          findRoots: "找出当前调全部主音",
          scaleRun: "音阶上行 / 下行提示"
        },
        showNames: "显示音名",
        hideNames: "隐藏音名",
        targetOnly: "只看目标",
        autoNext: "答对后自动下一题",
        chordRecognition: "和弦识别",
        newQuestion: "新题",
        showAnswer: "显示答案",
        cancelQuestion: "取消做题",
        resetStats: "重置统计",
        clearChord: "清空和弦",
        correctLabel: "正确",
        attemptsLabel: "尝试",
        start: "开始",
        stop: "停止",
        metroHelp: "首次点击开始时浏览器会启用声音。没有重音，适合均匀练音阶。",
        allNotesVisible: "所有音可见",
        scaleOnly: "只显示调内音",
        fixedDoNotes: "构成音",
        openString: "空弦",
        noQuestionTask: "点击“新题”开始。",
        noQuestionHint: "所有题目都用鼠标在指板上作答。",
        questionCanceled: "已取消做题。",
        chordOffStatus: "打开和弦识别后，在指板上点击音来识别和弦。",
        chordOnStatus: "每根弦只能选择一个音；再次点击同一位置可以取消。",
        chordNeedNotes: "至少选择 2 个音。",
        chordNoMatch: "没有找到明确匹配。可以继续加入 3 音、7 音或扩展音。",
        selectedNotesLabel: "已选音",
        noSelectedNotes: "暂无已选音。",
        chordOutsidePosition: "这个位置不在当前和弦识别把位范围内。",
        clickAnyCorrect: "点击任意一个正确位置即可通过。",
        chooseFixedName: "在下方选择这个位置的固定调音名。",
        currentKey: "当前调",
        rootProgress: "每个主音位置只需点击一次，进度会显示在下方。",
        up: "上行",
        down: "下行",
        findAllNote: note => `找到所有 ${note} 的位置`,
        identifyPosition: (string, fret) => `识别：${string} 第 ${fret} 品`,
        findDegree: degree => `点击当前调的第 ${degree} 级音`,
        findRoots: root => `找出所有 ${root} 主音`,
        scaleRunTitle: (root, mode, direction) => `${root} ${mode} ${direction}`,
        stepPrompt: (step, note) => `第 ${step} 个音：点击 ${note}`,
        clickedInfo: (string, fret, note) => `${string} 第 ${fret} 品：${note}`,
        positionIs: note => `这个位置是 ${note}。`,
        useButtons: "这题请用下方音名按钮作答。",
        correctNote: note => `正确：${note}。`,
        tryAgainThisIs: note => `再试一次：这是 ${note}。`,
        rootsFound: (found, total) => `已找到 ${found} / ${total} 个主音。`,
        notRoot: note => `这是 ${note}，不是主音。`,
        rootsDone: total => `完成：全部 ${total} 个主音都找到了。`,
        needNote: (target, hit) => `再试一次：当前要找 ${target}，你点到 ${hit}。`,
        scaleDone: "完成一轮音阶。",
        nextNote: note => `正确，下一音：${note}`,
        answerPosition: note => `答案：${note}。`,
        answerFindNote: note => `答案：点击任意 ${note}。`,
        answerFindDegree: (degree, note) => `答案：第 ${degree} 级是 ${note}。`,
        answerRoots: note => `答案：所有 ${note} 都是主音。`,
        answerScaleRun: note => `当前要点：${note}。`,
        nameAnswer: (string, fret, note) => `正确：${string} 第 ${fret} 品是 ${note}。`,
        wrongNameAnswer: note => `不对，这个位置是 ${note}。`,
        stringLabel: (number, note) => `${number}弦 ${note}`
      },
      en: {
        documentTitle: "Guitar Fretboard Scale Practice",
        appTitle: "Guitar Fretboard Scale Practice",
        appSubtitle: "Standard tuning, fixed / movable display, scale visualization, and click-based drills.",
        tonalityGroupTitle: "Tonality",
        materialGroupTitle: "Scales & Arpeggios",
        fretboardGroupTitle: "Fretboard",
        drillGroupTitle: "Drill Preferences",
        languageLabel: "Language",
        keyLabel: "Key",
        accidentalLabel: "Accidentals",
        materialLabel: "Material",
        modeLabel: "Pattern",
        fretCountLabel: "Frets",
        fretWindowLabel: "View range",
        visibilityLabel: "Scale display",
        solfegeLabel: "Display system",
        noteNameLabel: "Note names",
        practiceLabel: "Practice",
        scalePanelTitle: "Current Pattern",
        practicePanelTitle: "Drills",
        practiceTypeLabel: "Drill type",
        chordPanelTitle: "Chord Recognition",
        chordPositionLabel: "Position",
        metronomeTitle: "Metronome",
        tempoLabel: "Tempo",
        accidentalOptions: { sharp: "Sharps C#", flat: "Flats Db" },
        fretWindowOptions: { auto: "Auto", all: "All frets" },
        chordPositionOptions: { all: "All frets" },
        materialOptions: { scale: "Scale", arpeggio: "Arpeggio" },
        modeOptions: {
          major: "Major",
          naturalMinor: "Natural minor",
          harmonicMinor: "Harmonic minor",
          melodicMinor: "Jazz melodic minor",
          majorPentatonic: "Major pentatonic",
          minorPentatonic: "Minor pentatonic",
          majorTriad: "Major triad",
          minorTriad: "Minor triad",
          diminishedTriad: "Diminished triad",
          augmentedTriad: "Augmented triad",
          major7: "Maj7 arpeggio",
          dominant7: "Dom7 arpeggio",
          minor7: "Min7 arpeggio",
          halfDiminished7: "m7b5 arpeggio",
          diminished7: "Dim7 arpeggio",
          minorMajor7: "MinMaj7 arpeggio"
        },
        visibilityOptions: { highlight: "Show all notes, highlight scale tones", scaleOnly: "Show scale tones only" },
        solfegeOptions: { fixed: "Fixed: note names", movableNote: "Movable: solfege", degree: "Movable: degrees" },
        practiceTypeOptions: {
          findNote: "Given a note, click its position",
          identifyPosition: "Given a position, identify the note",
          findDegree: "Given a degree, click the note",
          findRoots: "Find all tonic notes",
          scaleRun: "Ascending / descending scale prompt"
        },
        showNames: "Show names",
        hideNames: "Hide names",
        targetOnly: "Target only",
        autoNext: "Auto next",
        chordRecognition: "Chord recognition",
        newQuestion: "New drill",
        showAnswer: "Show answer",
        cancelQuestion: "Cancel drill",
        resetStats: "Reset stats",
        clearChord: "Clear chord",
        correctLabel: "Correct",
        attemptsLabel: "Attempts",
        start: "Start",
        stop: "Stop",
        metroHelp: "Sound starts after your first click. No accents, just an even pulse for scale practice.",
        allNotesVisible: "All notes visible",
        scaleOnly: "Scale tones only",
        fixedDoNotes: "Pattern tones",
        openString: "Open",
        noQuestionTask: "Click “New drill” to start.",
        noQuestionHint: "Answer every drill by clicking on the fretboard.",
        questionCanceled: "Drill canceled.",
        chordOffStatus: "Turn on chord recognition, then click notes on the fretboard.",
        chordOnStatus: "One note per string. Click the same position again to remove it.",
        chordNeedNotes: "Select at least 2 notes.",
        chordNoMatch: "No clear match yet. Add a 3rd, 7th, or extension tone.",
        selectedNotesLabel: "Selected notes",
        noSelectedNotes: "No notes selected.",
        chordOutsidePosition: "That position is outside the current chord-recognition position.",
        clickAnyCorrect: "Click any correct position to pass.",
        chooseFixedName: "Choose the fixed note name below.",
        currentKey: "Current key",
        rootProgress: "Click each tonic position once. Progress appears below.",
        up: "ascending",
        down: "descending",
        findAllNote: note => `Find every ${note}`,
        identifyPosition: (string, fret) => `Identify: ${string}, fret ${fret}`,
        findDegree: degree => `Click scale degree ${degree}`,
        findRoots: root => `Find every ${root} tonic`,
        scaleRunTitle: (root, mode, direction) => `${root} ${mode}, ${direction}`,
        stepPrompt: (step, note) => `Step ${step}: click ${note}`,
        clickedInfo: (string, fret, note) => `${string}, fret ${fret}: ${note}`,
        positionIs: note => `This position is ${note}.`,
        useButtons: "Use the note-name buttons below for this drill.",
        correctNote: note => `Correct: ${note}.`,
        tryAgainThisIs: note => `Try again: this is ${note}.`,
        rootsFound: (found, total) => `Found ${found} / ${total} tonics.`,
        notRoot: note => `This is ${note}, not the tonic.`,
        rootsDone: total => `Done: all ${total} tonic notes found.`,
        needNote: (target, hit) => `Try again: find ${target}; you clicked ${hit}.`,
        scaleDone: "Scale run complete.",
        nextNote: note => `Correct, next note: ${note}`,
        answerPosition: note => `Answer: ${note}.`,
        answerFindNote: note => `Answer: click any ${note}.`,
        answerFindDegree: (degree, note) => `Answer: degree ${degree} is ${note}.`,
        answerRoots: note => `Answer: every ${note} is a tonic.`,
        answerScaleRun: note => `Current target: ${note}.`,
        nameAnswer: (string, fret, note) => `Correct: ${string}, fret ${fret} is ${note}.`,
        wrongNameAnswer: note => `Nope, this position is ${note}.`,
        stringLabel: (number, note) => `String ${number} ${note}`
      }
    };